using System.Linq;
using System.Text.Json;
using L5R.Engine.GameSteps;
using L5R.Engine.Logging;
using L5R.Engine.Randomness;
using L5R.Engine.Scheduling;
using L5R.Engine.State;

namespace L5R.Engine.Tests.Harness;

public sealed record HarnessResult(GameState Game, EventLog EventLog, StepState FinalState);

/// <summary>
/// Roadmap step 11: "an executable/test that runs a complete game between two trivial
/// strategies" - the assembled, reusable form of M1-M6's pieces (GameFactory/GameSetup/
/// GameLoop/ConflictResolver/EventLog/SeededRandom), all wired together into the one
/// canonical way this engine plays an actual game end to end, no UI. M8's golden replay
/// fixtures are generated by calling this same method.
///
/// Lives in the test project, not L5R.Engine.src, for a concrete practical reason: card JSON
/// is only ever copied to disk relative to the *test* project's own output directory (see
/// L5R.Engine.Tests.csproj's CopyToOutputDirectory items) - CardFactory/AbilityDefinitionParser
/// deliberately never touch the filesystem themselves (JsonElement in, Card out), so whoever
/// resolves an id to a document has to know where the files live. A production/Unity harness
/// would resolve ids through its own asset pipeline instead; this one uses the same
/// AppContext.BaseDirectory path every other per-card test already relies on.
/// </summary>
public static class BotVsBotHarness
{
    private static readonly string CardsDir = Path.Combine(AppContext.BaseDirectory, "Cards", "01-Core");

    private static JsonElement LoadJson(string cardId)
    {
        var path = Path.Combine(CardsDir, $"{cardId}.json");
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        return document.RootElement.Clone();
    }

    /// <summary>
    /// A small, fixed, generic-DSL-only Core Set deck - no scriptOverride cards, since the
    /// bot's action space doesn't cover them yet (the plan's own Phase B, tracked separately).
    /// Both players use the same decklist; nothing about the harness requires that, it's just
    /// the simplest fixed pool that still exercises real stats/skills/provinces/rings end to end.
    /// </summary>
    public static DeckList FixedDeck() => new(
        Stronghold: LoadJson("city-of-the-open-hand"),
        Role: null,
        DynastyCards: new[] { "moto-horde", "naive-student", "serene-warrior", "unassuming-yojimbo", "tattooed-wanderer", "kaiu-envoy" }.Select(LoadJson).ToArray(),
        ConflictCards: new[] { "bayushi-liar", "doji-whisperer", "eager-scout", "kaiu-envoy", "matsu-berserker", "serene-warrior" }.Select(LoadJson).ToArray());

    public static HarnessResult RunGame(ulong seed, IBotPolicy player1Policy, IBotPolicy player2Policy, int roundCap = 50)
    {
        var p1 = new Player { Name = "Player1" };
        var p2 = new Player { Name = "Player2" };
        var game = new GameState { Player1 = p1, Player2 = p2, ActivePlayer = p1 };
        var eventLog = new EventLog();

        var deck = FixedDeck();
        GameSetup.SetUpGame(game, deck, deck, new SeededRandom(seed), eventLog);

        var scheduler = new Scheduler();
        var loop = new GameLoop(game, scheduler, player1Policy, player2Policy, roundCap, eventLog);
        loop.Start();
        var finalState = scheduler.Pump();

        return new HarnessResult(game, eventLog, finalState);
    }
}
