using System.Linq;
using System.Text.Json;
using L5R.Engine.GameSteps;
using L5R.Engine.Logging;
using L5R.Engine.Randomness;
using L5R.Engine.Scheduling;
using L5R.Engine.State;

namespace L5R.Engine.Tests.Harness;

public sealed record HarnessResult(GameState Game, EventLog EventLog, StepState FinalState);

/// <summary>
/// Roadmap step 11: "an executable/test that runs a complete game between two trivial
/// strategies" - the assembled, reusable form of M1-M6's pieces (GameFactory/GameSetup/
/// GameLoop/ConflictResolver/EventLog/SeededRandom), all wired together into the one
/// canonical way this engine plays an actual game end to end, no UI. M8's golden replay
/// fixtures are generated by calling this same method.
///
/// Lives in the test project, not L5R.Engine.src, for a concrete practical reason: card JSON
/// is only ever copied to disk relative to the *test* project's own output directory (see
/// L5R.Engine.Tests.csproj's CopyToOutputDirectory items) - CardFactory/AbilityDefinitionParser
/// deliberately never touch the filesystem themselves (JsonElement in, Card out), so whoever
/// resolves an id to a document has to know where the files live. A production/Unity harness
/// would resolve ids through its own asset pipeline instead; this one uses the same
/// AppContext.BaseDirectory path every other per-card test already relies on.
/// </summary>
public static class BotVsBotHarness
{
    private static readonly string CardsDir = Path.Combine(AppContext.BaseDirectory, "Cards", "01-Core");

    private static JsonElement LoadJson(string cardId)
    {
        var path = Path.Combine(CardsDir, $"{cardId}.json");
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        return document.RootElement.Clone();
    }

    /// <summary>
    /// A small, fixed, generic-DSL-only Core Set deck. Both players use the same decklist;
    /// nothing about the harness requires that, it's just the simplest fixed pool that still
    /// exercises real stats/skills/provinces/rings end to end. Backs the original 4 golden
    /// fixtures - left untouched so they never need regenerating for an unrelated reason;
    /// see RichDeck for the deck that actually exercises the completed scriptOverride/Phase B
    /// bot action space.
    /// </summary>
    public static DeckList FixedDeck() => new(
        Stronghold: LoadJson("city-of-the-open-hand"),
        Role: null,
        DynastyCards: new[] { "moto-horde", "naive-student", "serene-warrior", "unassuming-yojimbo", "tattooed-wanderer", "kaiu-envoy" }.Select(LoadJson).ToArray(),
        ConflictCards: new[] { "bayushi-liar", "doji-whisperer", "eager-scout", "kaiu-envoy", "matsu-berserker", "serene-warrior" }.Select(LoadJson).ToArray());

    /// <summary>
    /// Now that every scriptOverride card is bot-drivable (either through
    /// ScriptedActionRegistry or a dedicated firer/offerer - see ScriptedActionRegistry's own
    /// doc comment), this deck deliberately mixes several of them in with plain generic-DSL
    /// cards: two registry-driven holdings (artisan-academy, secluded-temple), a firer-driven
    /// character (akodo-gunso, needs Card.ProvinceSlot), a registry-driven character
    /// (solemn-scholar), three registry-driven events (banzai, i-am-ready, outwit), and one
    /// offerer-driven event (way-of-the-unicorn). Requires the caller to construct each
    /// FirstLegalActionBotPolicy with a real ScriptedActionRegistry, or the registry-driven
    /// half is unreachable (ChooseScriptedAction/ResolveEventScript both short-circuit to
    /// null on a null registry) - see BotVsBotHarnessTests' own doc comment for the further
    /// caveat that even with the registry wired, this deck's small 6-card conflict pool and
    /// the trivial bot's pre-conflict-only hand-play timing mean the registry-driven cards
    /// still may never reach a legal firing window in a specific run; only the firer/offerer
    /// half is guaranteed to fire, since those are hooked unconditionally into shared
    /// production choke points rather than gated behind a bot's own action choice.
    /// </summary>
    public static DeckList RichDeck() => new(
        Stronghold: LoadJson("city-of-the-open-hand"),
        Role: null,
        DynastyCards: new[] { "artisan-academy", "secluded-temple", "akodo-gunso", "solemn-scholar", "naive-student", "unassuming-yojimbo" }.Select(LoadJson).ToArray(),
        ConflictCards: new[] { "banzai", "i-am-ready", "outwit", "way-of-the-unicorn", "eager-scout", "bayushi-liar" }.Select(LoadJson).ToArray());

    /// <summary>deck defaults to FixedDeck so every existing call site (3 harness tests, 4 golden fixtures) is unaffected.</summary>
    public static HarnessResult RunGame(ulong seed, IBotPolicy player1Policy, IBotPolicy player2Policy, int roundCap = 50, DeckList? deck = null)
    {
        var p1 = new Player { Name = "Player1" };
        var p2 = new Player { Name = "Player2" };
        var game = new GameState { Player1 = p1, Player2 = p2, ActivePlayer = p1 };
        var eventLog = new EventLog();

        var actualDeck = deck ?? FixedDeck();
        GameSetup.SetUpGame(game, actualDeck, actualDeck, new SeededRandom(seed), eventLog);

        var scheduler = new Scheduler();
        var loop = new GameLoop(game, scheduler, player1Policy, player2Policy, roundCap, eventLog);
        loop.Start();
        var finalState = scheduler.Pump();

        return new HarnessResult(game, eventLog, finalState);
    }
}
