using System.Text.Json;
using L5R.Engine.Tests.Schema;

namespace L5R.Engine.Tests.Cards;

/// <summary>
/// Every authored Core Set card must also validate against card-schema.json itself, not
/// just load through CardLoader - the two checks catch different things (CardLoader
/// checks names are registered; the schema checks shape/structure).
/// </summary>
public class CoreSetCardsSchemaValidationTests
{
    private static readonly string CardsDir = Path.Combine(AppContext.BaseDirectory, "Cards", "01-Core");

    [TestCase("hiruma-yojimbo")]
    [TestCase("border-rider")]
    [TestCase("cloud-the-mind")]
    [TestCase("assassination")]
    [TestCase("court-mask")]
    [TestCase("ancestral-lands")]
    [TestCase("city-of-the-open-hand")]
    [TestCase("artisan-academy")]
    [TestCase("keeper-of-air")]
    [TestCase("magnificent-kimono")]
    [TestCase("for-shame")]
    [TestCase("steadfast-samurai")]
    [TestCase("shiba-yojimbo")]
    [TestCase("favored-niece")]
    [TestCase("agasha-swordsmith")]
    [TestCase("shiba-tsukune")]
    [TestCase("niten-master")]
    [TestCase("guest-of-honor")]
    [TestCase("hida-guardian")]
    [TestCase("grasp-of-earth")]
    [TestCase("cautious-scout")]
    [TestCase("seppun-guardsman")]
    [TestCase("duelist-training")]
    [TestCase("tattooed-wanderer")]
    [TestCase("kaiu-shuichi")]
    [TestCase("favored-mount")]
    [TestCase("asahina-artisan")]
    [TestCase("otomo-courtier")]
    [TestCase("mirumoto-prodigy")]
    [TestCase("venerable-historian")]
    [TestCase("guidance-of-the-ancestors")]
    [TestCase("togashi-initiate")]
    [TestCase("moto-youth")]
    [TestCase("seeker-of-knowledge")]
    [TestCase("fertile-fields")]
    [TestCase("shinjo-outrider")]
    [TestCase("height-of-fashion")]
    [TestCase("above-question")]
    [TestCase("adept-of-shadows")]
    [TestCase("admit-defeat")]
    [TestCase("against-the-waves")]
    [TestCase("bayushi-yunako")]
    [TestCase("blackmail")]
    [TestCase("borderlands-defender")]
    [TestCase("born-in-war")]
    [TestCase("brash-samurai")]
    [TestCase("breakthrough")]
    [TestCase("calling-in-favors")]
    [TestCase("captive-audience")]
    [TestCase("ambush")]
    [TestCase("cavalry-reserves")]
    [TestCase("charge")]
    [TestCase("city-of-lies")]
    [TestCase("contingency-plan")]
    [TestCase("court-games")]
    [TestCase("daidoji-nerishma")]
    [TestCase("daimyo-s-favor")]
    [TestCase("deathseeker")]
    [TestCase("defend-the-wall")]
    [TestCase("display-of-power")]
    [TestCase("doji-challenger")]
    [TestCase("doji-gift-giver")]
    [TestCase("doomed-shugenja")]
    [TestCase("elemental-fury")]
    [TestCase("endless-plains")]
    [TestCase("enlightened-warrior")]
    [TestCase("entrenched-position")]
    [TestCase("fallen-in-battle")]
    [TestCase("favorable-ground")]
    [TestCase("fearsome-mystic")]
    [TestCase("for-greater-glory")]
    [TestCase("forged-edict")]
    [TestCase("forgotten-library")]
    [TestCase("funeral-pyre")]
    [TestCase("giver-of-gifts")]
    [TestCase("golden-plains-outpost")]
    [TestCase("good-omen")]
    [TestCase("hida-kisada")]
    [TestCase("hida-tomonatsu")]
    [TestCase("hiruma-ambusher")]
    [TestCase("honored-blade")]
    [TestCase("honored-general")]
    [TestCase("i-am-ready")]
    [TestCase("i-can-swim")]
    [TestCase("ide-messenger")]
    [TestCase("ide-trader")]
    [TestCase("ikoma-eiji")]
    [TestCase("ikoma-prodigy")]
    [TestCase("imperial-storehouse")]
    [TestCase("indomitable-will")]
    [TestCase("intimidating-hida")]
    [TestCase("isawa-atsuko")]
    [TestCase("isawa-masahiro")]
    [TestCase("isawa-mori-seido")]
    [TestCase("ishiken-initiate")]
    [TestCase("iuchi-wayfinder")]
    [TestCase("jade-tetsubo")]
    [TestCase("kakita-asami")]
    [TestCase("kakita-kaezin")]
    [TestCase("keeper-initiate")]
    [TestCase("keeper-of-earth")]
    [TestCase("keeper-of-fire")]
    [TestCase("keeper-of-void")]
    [TestCase("keeper-of-water")]
    [TestCase("kitsu-spiritcaller")]
    [TestCase("kitsuki-investigator")]
    [TestCase("know-the-world")]
    [TestCase("kuroi-mori")]
    [TestCase("let-go")]
    [TestCase("levy")]
    [TestCase("lion-s-pride-brawler")]
    [TestCase("manicured-garden")]
    [TestCase("mantra-of-fire")]
    [TestCase("master-of-the-spear")]
    [TestCase("matsu-beiona")]
    [TestCase("meddling-mediator")]
    [TestCase("meditations-on-the-tao")]
    [TestCase("meishodo-wielder")]
    [TestCase("mirumoto-raitsugu")]
    [TestCase("mirumoto-s-fury")]
    [TestCase("miya-mystic")]
    [TestCase("mountain-s-anvil-castle")]
    [TestCase("night-raid")]
    [TestCase("niten-adept")]
    [TestCase("noble-sacrifice")]
    [TestCase("obstinate-recruit")]
    [TestCase("outwit")]
    [TestCase("pacifism")]
    [TestCase("pilgrimage")]
    [TestCase("political-rival")]
    [TestCase("radiant-orator")]
    [TestCase("rally-to-the-cause")]
    [TestCase("ready-for-battle")]
    [TestCase("rebuild")]
    [TestCase("reprieve")]
    [TestCase("restoration-of-balance")]
    [TestCase("rout")]
    [TestCase("sashimono")]
    [TestCase("savvy-politician")]
    [TestCase("secluded-temple")]
    [TestCase("secret-cache")]
    [TestCase("seeker-initiate")]
    [TestCase("seeker-of-air")]
    [TestCase("seeker-of-earth")]
    [TestCase("seeker-of-enlightenment")]
    public void RealCoreSetCard_ValidatesAgainstTheSchema(string cardId)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(CardsDir, $"{cardId}.json")));

        var result = SharedCardSchema.Instance.Evaluate(document.RootElement);

        Assert.That(result.IsValid, Is.True, $"{cardId}.json must validate against card-schema.json");
    }
}
