using L5R.Engine.Cards;
using L5R.Engine.Cards.Scripts;

namespace L5R.Engine.Tests.Cards;

/// <summary>
/// Loads every authored Core Set card (L5R.Engine/cards/01-Core/) through CardLoader,
/// proving the schema/DSL and the registries actually hold up against real cards, not
/// just hand-built fixtures. Each card here was ported from a real ringteki
/// server/game/cards/01-Core/*.js implementation.
/// </summary>
public class CoreSetCardsTests
{
    private static readonly string CardsDir = Path.Combine(AppContext.BaseDirectory, "Cards", "01-Core");

    [TestCase("hiruma-yojimbo")]
    [TestCase("border-rider")]
    [TestCase("cloud-the-mind")]
    [TestCase("assassination")]
    [TestCase("court-mask")]
    [TestCase("ancestral-lands")]
    [TestCase("city-of-the-open-hand")]
    [TestCase("artisan-academy")]
    [TestCase("keeper-of-air")]
    [TestCase("magnificent-kimono")]
    [TestCase("for-shame")]
    [TestCase("steadfast-samurai")]
    [TestCase("shiba-yojimbo")]
    [TestCase("favored-niece")]
    [TestCase("agasha-swordsmith")]
    [TestCase("shiba-tsukune")]
    [TestCase("niten-master")]
    [TestCase("guest-of-honor")]
    [TestCase("hida-guardian")]
    [TestCase("grasp-of-earth")]
    [TestCase("cautious-scout")]
    [TestCase("seppun-guardsman")]
    [TestCase("duelist-training")]
    [TestCase("tattooed-wanderer")]
    [TestCase("kaiu-shuichi")]
    [TestCase("favored-mount")]
    [TestCase("asahina-artisan")]
    [TestCase("otomo-courtier")]
    [TestCase("mirumoto-prodigy")]
    [TestCase("venerable-historian")]
    [TestCase("guidance-of-the-ancestors")]
    [TestCase("togashi-initiate")]
    [TestCase("moto-youth")]
    [TestCase("seeker-of-knowledge")]
    [TestCase("fertile-fields")]
    [TestCase("shinjo-outrider")]
    [TestCase("height-of-fashion")]
    [TestCase("above-question")]
    [TestCase("adept-of-shadows")]
    [TestCase("admit-defeat")]
    [TestCase("against-the-waves")]
    [TestCase("bayushi-yunako")]
    [TestCase("blackmail")]
    [TestCase("borderlands-defender")]
    [TestCase("born-in-war")]
    [TestCase("brash-samurai")]
    [TestCase("breakthrough")]
    [TestCase("calling-in-favors")]
    [TestCase("captive-audience")]
    [TestCase("ambush")]
    [TestCase("cavalry-reserves")]
    [TestCase("charge")]
    [TestCase("city-of-lies")]
    [TestCase("contingency-plan")]
    [TestCase("court-games")]
    [TestCase("daidoji-nerishma")]
    [TestCase("daimyo-s-favor")]
    [TestCase("deathseeker")]
    [TestCase("defend-the-wall")]
    [TestCase("display-of-power")]
    [TestCase("doji-challenger")]
    [TestCase("doji-gift-giver")]
    [TestCase("doomed-shugenja")]
    [TestCase("elemental-fury")]
    [TestCase("endless-plains")]
    [TestCase("enlightened-warrior")]
    [TestCase("entrenched-position")]
    [TestCase("fallen-in-battle")]
    [TestCase("favorable-ground")]
    [TestCase("fearsome-mystic")]
    [TestCase("for-greater-glory")]
    [TestCase("forged-edict")]
    [TestCase("forgotten-library")]
    [TestCase("funeral-pyre")]
    [TestCase("giver-of-gifts")]
    [TestCase("golden-plains-outpost")]
    [TestCase("good-omen")]
    [TestCase("hida-kisada")]
    [TestCase("hida-tomonatsu")]
    [TestCase("hiruma-ambusher")]
    [TestCase("honored-blade")]
    [TestCase("honored-general")]
    [TestCase("i-am-ready")]
    [TestCase("i-can-swim")]
    [TestCase("ide-messenger")]
    [TestCase("ide-trader")]
    [TestCase("ikoma-eiji")]
    [TestCase("ikoma-prodigy")]
    [TestCase("imperial-storehouse")]
    [TestCase("indomitable-will")]
    [TestCase("intimidating-hida")]
    [TestCase("isawa-atsuko")]
    [TestCase("isawa-masahiro")]
    [TestCase("isawa-mori-seido")]
    [TestCase("ishiken-initiate")]
    [TestCase("iuchi-wayfinder")]
    [TestCase("jade-tetsubo")]
    [TestCase("kakita-asami")]
    [TestCase("kakita-kaezin")]
    [TestCase("keeper-initiate")]
    [TestCase("keeper-of-earth")]
    [TestCase("keeper-of-fire")]
    [TestCase("keeper-of-void")]
    [TestCase("keeper-of-water")]
    [TestCase("kitsu-spiritcaller")]
    [TestCase("kitsuki-investigator")]
    [TestCase("know-the-world")]
    [TestCase("kuroi-mori")]
    [TestCase("let-go")]
    [TestCase("levy")]
    [TestCase("lion-s-pride-brawler")]
    [TestCase("manicured-garden")]
    [TestCase("mantra-of-fire")]
    [TestCase("master-of-the-spear")]
    [TestCase("matsu-beiona")]
    [TestCase("meddling-mediator")]
    [TestCase("meditations-on-the-tao")]
    [TestCase("meishodo-wielder")]
    [TestCase("mirumoto-raitsugu")]
    [TestCase("mirumoto-s-fury")]
    [TestCase("miya-mystic")]
    [TestCase("mountain-s-anvil-castle")]
    [TestCase("night-raid")]
    [TestCase("niten-adept")]
    [TestCase("noble-sacrifice")]
    [TestCase("obstinate-recruit")]
    [TestCase("outwit")]
    [TestCase("pacifism")]
    [TestCase("pilgrimage")]
    [TestCase("political-rival")]
    [TestCase("radiant-orator")]
    [TestCase("rally-to-the-cause")]
    [TestCase("ready-for-battle")]
    [TestCase("rebuild")]
    [TestCase("reprieve")]
    [TestCase("restoration-of-balance")]
    [TestCase("rout")]
    [TestCase("sashimono")]
    [TestCase("savvy-politician")]
    [TestCase("secluded-temple")]
    [TestCase("secret-cache")]
    [TestCase("seeker-initiate")]
    [TestCase("seeker-of-air")]
    [TestCase("seeker-of-earth")]
    [TestCase("seeker-of-enlightenment")]
    [TestCase("seeker-of-fire")]
    [TestCase("shameful-display")]
    [TestCase("shiba-peacemaker")]
    [TestCase("shinjo-altansarnai")]
    [TestCase("shinjo-tatsuo")]
    [TestCase("shiro-nishiyama")]
    [TestCase("shizuka-toshi")]
    [TestCase("shosuro-actress")]
    [TestCase("shosuro-miyako")]
    [TestCase("shrewd-yasuki")]
    [TestCase("sinister-soshi")]
    [TestCase("soshi-illusionist")]
    [TestCase("spies-at-court")]
    [TestCase("spyglass")]
    [TestCase("staging-ground")]
    [TestCase("stand-your-ground")]
    [TestCase("steadfast-witch-hunter")]
    [TestCase("steward-of-law")]
    [TestCase("stoic-gunso")]
    [TestCase("strength-in-numbers")]
    [TestCase("supernatural-storm")]
    [TestCase("the-art-of-peace")]
    [TestCase("the-art-of-war")]
    [TestCase("the-mountain-does-not-fall")]
    [TestCase("the-perfect-gift")]
    [TestCase("togashi-kazue")]
    [TestCase("togashi-yokuni")]
    [TestCase("tranquility")]
    [TestCase("utaku-infantry")]
    [TestCase("utaku-yumino")]
    [TestCase("vanguard-warrior")]
    [TestCase("vengeful-berserker")]
    [TestCase("vengeful-oathkeeper")]
    [TestCase("voice-of-honor")]
    [TestCase("wandering-ronin")]
    [TestCase("warrior-poet")]
    [TestCase("watch-commander")]
    [TestCase("way-of-the-crab")]
    [TestCase("way-of-the-crane")]
    [TestCase("way-of-the-dragon")]
    [TestCase("way-of-the-lion")]
    [TestCase("way-of-the-phoenix")]
    [TestCase("way-of-the-scorpion")]
    [TestCase("way-of-the-unicorn")]
    [TestCase("yogo-hiroue")]
    [TestCase("yogo-outcast")]
    [TestCase("yojin-no-shiro")]
    [TestCase("young-rumormonger")]
    public void RealCoreSetCard_LoadsWithoutError(string cardId)
    {
        var loader = new CardLoader(RingtekiCatalog.Effects, RingtekiCatalog.GameActions, RingtekiCatalog.Costs);
        var path = Path.Combine(CardsDir, $"{cardId}.json");

        Assert.That(File.Exists(path), Is.True, $"expected a card file at {path}");

        var card = loader.Load(File.ReadAllText(path));

        Assert.That(card.Id, Is.EqualTo(cardId));
    }

    [Test]
    public void CloudTheMind_ResolvesItsScriptOverrideHandler()
    {
        var loader = new CardLoader(RingtekiCatalog.Effects, RingtekiCatalog.GameActions, RingtekiCatalog.Costs);
        var path = Path.Combine(CardsDir, "cloud-the-mind.json");

        var card = loader.Load(File.ReadAllText(path));

        Assert.That(card.ScriptOverride, Is.Not.Null);
        Assert.That(card.ScriptOverride!.HandlerType, Is.EqualTo(typeof(CloudTheMindPlayRestriction)));
        Assert.That(card.ScriptOverride!.Reason, Is.Not.Empty, "scriptOverride must document why it was needed");
    }

    [TestCase("artisan-academy", typeof(ArtisanAcademyRevealTopCard))]
    [TestCase("keeper-of-air", typeof(KeeperOfAirGainFateOnDefendedWin))]
    [TestCase("steadfast-samurai", typeof(SteadfastSamuraiHonorThresholdProtection))]
    [TestCase("shiba-yojimbo", typeof(ShibaYojimboCancelShugenjaTargetedAbility))]
    [TestCase("shiba-tsukune", typeof(ShibaTsukuneResolveUpToTwoRings))]
    [TestCase("niten-master", typeof(NitenMasterReadyOnWeaponAttached))]
    [TestCase("cautious-scout", typeof(CautiousScoutBlankLoneAttackersProvince))]
    [TestCase("duelist-training", typeof(DuelistTrainingGrantMilitaryDuelAction))]
    [TestCase("tattooed-wanderer", typeof(TattooedWandererPlayAsAttachment))]
    [TestCase("blackmail", typeof(BlackmailCannotPlayUnlessLessHonorable))]
    [TestCase("breakthrough", typeof(BreakthroughDeclareSecondConflict))]
    [TestCase("calling-in-favors", typeof(CallingInFavorsAttachOrDiscard))]
    [TestCase("court-games", typeof(CourtGamesHonorOrDishonorParticipant))]
    [TestCase("deathseeker", typeof(DeathseekerRemoveFateOrDiscardOnLoss))]
    [TestCase("defend-the-wall", typeof(DefendTheWallResolveRingAsAttacker))]
    [TestCase("display-of-power", typeof(DisplayOfPowerCancelAndClaimRing))]
    [TestCase("endless-plains", typeof(EndlessPlainsBreakAndDiscardAttacker))]
    [TestCase("enlightened-warrior", typeof(EnlightenedWarriorGainFateOnOpponentRingSelect))]
    [TestCase("fallen-in-battle", typeof(FallenInBattleDiscardOnDecisiveMilitaryWin))]
    [TestCase("fearsome-mystic", typeof(FearsomeMysticRemoveFateFromLowerGloryOpponents))]
    [TestCase("for-greater-glory", typeof(ForGreaterGloryPlaceFateOnBushi))]
    [TestCase("forgotten-library", typeof(ForgottenLibraryDrawOnDrawPhase))]
    [TestCase("good-omen", typeof(GoodOmenCannotPlayWithoutComposure))]
    [TestCase("giver-of-gifts", typeof(GiverOfGiftsMoveAttachment))]
    [TestCase("hida-kisada", typeof(HidaKisadaCancelOpponentsFirstActionEachConflict))]
    [TestCase("hida-tomonatsu", typeof(HidaTomonatsuReturnAttackerToDeckOnDefendedWin))]
    [TestCase("honored-blade", typeof(HonoredBladeGainHonorWhenParentWins))]
    [TestCase("i-am-ready", typeof(IAmReadyReadyTheRemoveFateCostTarget))]
    [TestCase("ide-trader", typeof(IdeTraderGainFateOrDrawOnAllyMovingToConflict))]
    [TestCase("ikoma-eiji", typeof(IkomaEijiPutBushiIntoPlayOnPoliticalLoss))]
    [TestCase("ikoma-prodigy", typeof(IkomaProdigyGainHonorWhenFateAddedOrMoved))]
    [TestCase("indomitable-will", typeof(IndomitableWillPreventBowOnSoloWin))]
    [TestCase("intimidating-hida", typeof(IntimidatingHidaLoseHonorOnOpponentPass))]
    [TestCase("jade-tetsubo", typeof(JadeTetsuboReturnFateFromLowerMilitaryParticipant))]
    [TestCase("kakita-asami", typeof(KakitaAsamiTakeHonorWhenWinningPoliticalSkill))]
    [TestCase("kakita-kaezin", typeof(KakitaKaezinDuelAndSendHomeByOutcome))]
    [TestCase("keeper-initiate", typeof(KeeperInitiatePutIntoPlayOnMatchingRingClaim))]
    [TestCase("keeper-of-earth", typeof(KeeperOfEarthGainFateOnEarthDefenseWin))]
    [TestCase("keeper-of-fire", typeof(KeeperOfFireGainFateOnFireDefenseWin))]
    [TestCase("keeper-of-void", typeof(KeeperOfVoidGainFateOnVoidDefenseWin))]
    [TestCase("keeper-of-water", typeof(KeeperOfWaterGainFateOnWaterDefenseWin))]
    [TestCase("kitsu-spiritcaller", typeof(KitsuSpiritcallerResurrectUntilConflictEnd))]
    [TestCase("lion-s-pride-brawler", typeof(LionsPrideBrawlerBowLowerMilitarySkill))]
    [TestCase("mantra-of-fire", typeof(MantraOfFireAddFateToMonkAndDraw))]
    [TestCase("meddling-mediator", typeof(MeddlingMediatorTakeFateOrHonorWhenDoublyAttacked))]
    [TestCase("meishodo-wielder", typeof(MeishodoWielderReduceCostWhileFirstPlayer))]
    [TestCase("mirumoto-raitsugu", typeof(MirumotoRaitsuguDuelAndPunishLoser))]
    [TestCase("mountain-s-anvil-castle", typeof(MountainsAnvilCastleBonusForAttachments))]
    [TestCase("niten-adept", typeof(NitenAdeptBowAttachmentToBowUnattachedParticipant))]
    [TestCase("obstinate-recruit", typeof(ObstinateRecruitDiscardWhenOpponentMoreHonorable))]
    [TestCase("outwit", typeof(OutwitSendHomeOutclassedByCourtier))]
    [TestCase("pacifism", typeof(PacifismCannotPlayDuringConflict))]
    [TestCase("pilgrimage", typeof(PilgrimageCancelRingEffectsAtThisProvince))]
    [TestCase("radiant-orator", typeof(RadiantOratorSendHomeWhenAheadOnGlory))]
    [TestCase("ready-for-battle", typeof(ReadyForBattleReadyOnOpponentOrRingBow))]
    [TestCase("rebuild", typeof(RebuildReplaceProvinceCardWithHolding))]
    [TestCase("reprieve", typeof(ReprieveDiscardInsteadOfParentLeavingPlay))]
    [TestCase("rout", typeof(RoutSendHomeOutclassedByBushi))]
    [TestCase("secluded-temple", typeof(SecludedTempleRemoveFateWhenOutnumbered))]
    [TestCase("secret-cache", typeof(SecretCacheSearchTopFiveOnConflictDeclared))]
    [TestCase("seeker-initiate", typeof(SeekerInitiateSearchTopFiveOnMatchingRingClaim))]
    [TestCase("seeker-of-air", typeof(SeekerOfAirGainFateOnMatchingProvinceReveal))]
    [TestCase("seeker-of-earth", typeof(SeekerOfEarthGainFateOnMatchingProvinceReveal))]
    [TestCase("seeker-of-enlightenment", typeof(SeekerOfEnlightenmentBonusForFateOnUnclaimedRings))]
    [TestCase("seeker-of-fire", typeof(SeekerOfFireGainFateOnMatchingProvinceReveal))]
    [TestCase("shameful-display", typeof(ShamefulDisplayHonorOneDishonorOther))]
    [TestCase("shinjo-altansarnai", typeof(ShinjoAltansarnaiDiscardOnMilitaryProvinceBreak))]
    [TestCase("shinjo-tatsuo", typeof(ShinjoTatsuoMoveSelfAndOptionalAllyToConflict))]
    [TestCase("shosuro-miyako", typeof(ShosuroMiyakoDiscardOrDishonorOnCharacterPlayed))]
    [TestCase("shrewd-yasuki", typeof(ShrewdYasukiLookAtTopTwoKeepOne))]
    [TestCase("spies-at-court", typeof(SpiesAtCourtDiscardTwoOnPoliticalWin))]
    [TestCase("spyglass", typeof(SpyglassDrawOnParentJoiningConflict))]
    [TestCase("stand-your-ground", typeof(StandYourGroundDiscardTokenInsteadOfLeavingPlay))]
    [TestCase("strength-in-numbers", typeof(StrengthInNumbersSendHomeLowGloryDefender))]
    [TestCase("the-perfect-gift", typeof(ThePerfectGiftRevealAndGiveEachPlayerACard))]
    [TestCase("togashi-kazue", typeof(TogashiKazuePlayAsAttachmentOrCharacter))]
    [TestCase("togashi-yokuni", typeof(TogashiYokuniCopyAnotherCharactersAbility))]
    [TestCase("vengeful-berserker", typeof(VengefulBerserkerDoubleMilitaryOnAllyLeavingPlay))]
    [TestCase("vengeful-oathkeeper", typeof(VengefulOathkeeperPutIntoPlayOnMilitaryLoss))]
    [TestCase("watch-commander", typeof(WatchCommanderLoseHonorOnOpponentCardPlayed))]
    [TestCase("way-of-the-phoenix", typeof(WayOfThePhoenixPreventOpponentDeclaringRingElement))]
    [TestCase("way-of-the-unicorn", typeof(WayOfTheUnicornKeepFirstPlayerToken))]
    [TestCase("yogo-hiroue", typeof(YogoHiroueMoveThenMayDishonorOnWin))]
    [TestCase("young-rumormonger", typeof(YoungRumormongerRedirectHonorOrDishonor))]
    public void Card_ResolvesItsScriptOverrideHandler(string cardId, Type expectedHandlerType)
    {
        var loader = new CardLoader(RingtekiCatalog.Effects, RingtekiCatalog.GameActions, RingtekiCatalog.Costs);
        var path = Path.Combine(CardsDir, $"{cardId}.json");

        var card = loader.Load(File.ReadAllText(path));

        Assert.That(card.ScriptOverride, Is.Not.Null);
        Assert.That(card.ScriptOverride!.HandlerType, Is.EqualTo(expectedHandlerType));
        Assert.That(card.ScriptOverride!.Reason, Is.Not.Empty, "scriptOverride must document why it was needed");
    }

    [TestCase("kaiu-shuichi")]
    [TestCase("grasp-of-earth")]
    [TestCase("mirumoto-prodigy")]
    [TestCase("admit-defeat")]
    public void Card_NoLongerNeedsScriptOverride_AfterTheVocabularyGrewToCoverIt(string cardId)
    {
        // kaiu-shuichi needed a per-player dynamic count (valueRef "for"); grasp-of-earth
        // needed a bulk-collection gameAction target ("allCardsMatching"); mirumoto-prodigy
        // and admit-defeat needed a per-role conflict participant count (valueRef "role").
        // All were originally scriptOverride; this pins down that they now load generically.
        var loader = new CardLoader(RingtekiCatalog.Effects, RingtekiCatalog.GameActions, RingtekiCatalog.Costs);
        var path = Path.Combine(CardsDir, $"{cardId}.json");

        var card = loader.Load(File.ReadAllText(path));

        Assert.That(card.ScriptOverride, Is.Null);
    }
}
